let data;
export default data = {
    "status": 0,
    "httpCode": 200,
    "message": "请求成功",
    "data": {
        "list": [
            {
                "id": 1478,
                "type": 0,
                "createTime": 1609430754946,
                "content": "<p>祝各位新年快乐🤣🤣🤣🤣🤣🤣🙌🙌🙌🙌🙌</p>",
                "userId": 95,
                "userIsAdmin": 1,
                "userName": "王老师",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1476,
                "type": 0,
                "createTime": 1609384879174,
                "content": "<p>hooks+ts实现的移动端组件库，已经完成了90%。</p>",
                "userId": 95,
                "userIsAdmin": 1,
                "userName": "王老师",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1475,
                "type": 0,
                "createTime": 1609384808023,
                "content": "<p>马上要2021了，2020的目标都没实现😌</p>",
                "userId": 95,
                "userIsAdmin": 1,
                "userName": "王老师",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": [
                    {
                        "id": 1477,
                        "type": 1,
                        "createTime": 1609384921439,
                        "content": "希望2021更好点",
                        "userId": 95,
                        "userIsAdmin": 1,
                        "userName": "王老师",
                        "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "targetUserId": 95,
                        "targetUserIsAdmin": 1,
                        "targetUserName": "王老师",
                        "targetUserAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "pid": 1475,
                        "likeNum": 0
                    }
                ]
            },
            {
                "id": 1473,
                "type": 0,
                "createTime": 1609327143922,
                "content": "<p>&lt; a href=&quot;https://mp.weixin.qq.com/s/578eGVBlY6JUOUkCmqzRiA &quot;&gt;点击跳小程序&lt;/ a&gt;</p>",
                "userId": 109,
                "userIsAdmin": 0,
                "userName": "123456",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1472,
                "type": 0,
                "createTime": 1609322912249,
                "content": "<p>东方   放</p><p></p><p></p><p>放</p><p></p><p></p><p>放</p>",
                "userId": 109,
                "userIsAdmin": 0,
                "userName": "123456",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1471,
                "type": 0,
                "createTime": 1609322904744,
                "content": "<p>&lt;a href=&quot;https://mp.weixin.qq.com/s/578eGVBlY6JUOUkCmqzRiA1&quot; target=&quot;&quot;&gt;我是链接&lt;/a&gt;</p>",
                "userId": 109,
                "userIsAdmin": 0,
                "userName": "123456",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1462,
                "type": 0,
                "createTime": 1608804000249,
                "content": "<p>66666</p>",
                "userId": 4142,
                "userIsAdmin": 0,
                "userName": "123566",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            },
            {
                "id": 1461,
                "type": 0,
                "createTime": 1608704152185,
                "content": "<p></p><div class=\"media-wrap video-wrap\"><video controls=\"\" src=\"https://cz-video-view.oss-cn-beijing.aliyuncs.com/20191019/c16eb2bda06db942c68d4169eab1ec39.mp4\"></video></div><p></p>",
                "userId": 4133,
                "userIsAdmin": 0,
                "userName": "Aa111111",
                "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": [
                    {
                        "id": 1467,
                        "type": 1,
                        "createTime": 1609314563008,
                        "content": "6",
                        "userId": 3812,
                        "userIsAdmin": 0,
                        "userName": "admin1230945",
                        "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "targetUserId": 4133,
                        "targetUserIsAdmin": 0,
                        "targetUserName": "Aa111111",
                        "targetUserAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "pid": 1461,
                        "likeNum": 0
                    }
                ]
            },
            {
                "id": 1458,
                "type": 0,
                "createTime": 1608690554586,
                "content": "<p></p><div class=\"media-wrap image-wrap\"><img src=\"http://47.99.130.140:8888/myUpload/logo.png\"/></div><p></p>",
                "userId": 4128,
                "userIsAdmin": 0,
                "userName": "gzx97",
                "userAvatar": "http://47.99.130.140:8888/myUpload/sm_card_dmo.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": [
                    {
                        "id": 1459,
                        "type": 1,
                        "createTime": 1608703734743,
                        "content": "123",
                        "userId": 4116,
                        "userIsAdmin": 0,
                        "userName": "test123456..",
                        "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "targetUserId": 4128,
                        "targetUserIsAdmin": 0,
                        "targetUserName": "gzx97",
                        "targetUserAvatar": "http://47.99.130.140:8888/myUpload/sm_card_dmo.png",
                        "pid": 1458,
                        "likeNum": 0
                    },
                    {
                        "id": 1460,
                        "type": 1,
                        "createTime": 1608703770498,
                        "content": "132132",
                        "userId": 4116,
                        "userIsAdmin": 0,
                        "userName": "test123456..",
                        "userAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "targetUserId": 4116,
                        "targetUserIsAdmin": 0,
                        "targetUserName": "test123456..",
                        "targetUserAvatar": "http://47.99.130.140:8888/public/images/default.png",
                        "pid": 1458,
                        "likeNum": 0
                    }
                ]
            },
            {
                "id": 1457,
                "type": 0,
                "createTime": 1608690540186,
                "content": "<p></p><div class=\"media-wrap image-wrap align-right\" style=\"text-align:right\"><img src=\"http://47.99.130.140:8888/myUpload/30logo.png\"/></div><p></p>",
                "userId": 4128,
                "userIsAdmin": 0,
                "userName": "gzx97",
                "userAvatar": "http://47.99.130.140:8888/myUpload/sm_card_dmo.png",
                "targetUserId": null,
                "targetUserIsAdmin": null,
                "targetUserName": null,
                "targetUserAvatar": null,
                "pid": -1,
                "likeNum": 0,
                "children": []
            }
        ],
        "current": 0,
        "pageSize": 10,
        "total": 14
    }
}
