# Generated by Django 3.0.3 on 2020-12-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('course_name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('credit', models.FloatField(verbose_name='学分')),
                ('department', models.CharField(max_length=64, verbose_name='开课学院')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '课程表',
                'db_table': 'course_sre',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='教学班编号')),
                ('startTime', models.DateField(verbose_name='开始时间')),
                ('endTime', models.DateField(null=True, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learning_in_zju.Course', verbose_name='课程编号')),
            ],
            options={
                'verbose_name_plural': '教学班表',
                'db_table': 'section_sre',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知编号')),
                ('title', models.CharField(max_length=50, verbose_name='通知标题')),
                ('content', models.CharField(max_length=512, verbose_name='通知内容')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learning_in_zju.Course', verbose_name='课程编号')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learning_in_zju.Section', verbose_name='班级编号')),
            ],
            options={
                'verbose_name_plural': '课程通知表',
                'db_table': 'notice_sre',
            },
        ),
    ]
