# Generated by Django 3.0.3 on 2020-12-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('learning_in_zju', '0002_course_notice_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='learning_in_zju.User', verbose_name='用户编号'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='Notice_sre',
        ),
        migrations.AlterModelTable(
            name='section',
            table='Section',
        ),
    ]
