# Generated by Django 3.0.3 on 2020-12-04 09:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('learning_in_zju', '0004_auto_20201204_1737'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='Notice',
        ),
        migrations.AlterModelTable(
            name='section',
            table='Section',
        ),
    ]
