# Generated by Django 3.0.3 on 2020-12-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0006_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=models.CharField(default=' ', max_length=512, verbose_name='课程简介'),
        ),
    ]
