# Generated by Django 3.0.3 on 2020-12-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0008_section2student_section2teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section2student',
            table='section2student',
        ),
        migrations.AlterModelTable(
            name='section2teacher',
            table='section2teacher',
        ),
    ]
