# Generated by Django 3.0.3 on 2020-12-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0009_auto_20201228_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2student',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='section2student',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='section2teacher',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='section2teacher',
            name='modify_time',
        ),
    ]
