# Generated by Django 3.0.3 on 2021-01-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0010_auto_20201228_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='modify_time',
        ),
    ]
