# Generated by Django 3.0.3 on 2020-12-04 09:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('learning_in_zju', '0003_auto_20201204_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course_sre',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notice_sre',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section_sre',
        ),
    ]
