# Generated by Django 3.0.3 on 2020-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_in_zju', '0005_auto_20201204_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
